global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'locust'
    static_configs:
      - targets: ['host.docker.internal:9646']  # Use host.docker.internal to access host machine 