# Req res List of user base path
REQ_RES_USERS_LIST_BASE_PATHS = "/api/users"
DUMMY_JSON_LOGIN = "/auth/login"
DUMMY_JSON_CURRENT_AUTH_USER = "/auth/me"

# Combine all paths
BASE_PATHS = {
    "REQ_RES_USERS_LIST_BASE_PATHS": REQ_RES_USERS_LIST_BASE_PATHS,
    "DUMMY_JSON_LOGIN": DUMMY_JSON_LOGIN,
    "DUMMY_JSON_CURRENT_AUTH_USER": DUMMY_JSON_CURRENT_AUTH_USER
}
